apiVersion: v1
kind: ConfigMap
metadata:
  name: testrunner-env
data:
  TestRunnerPort: "80"
  LogFile: "out.log"

---

apiVersion: v1
kind: Service
metadata:
  name: testrunner-service
spec:
  selector:
    app: testrunner
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testrunner-deployment
  labels:
    app: testrunner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testrunner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testrunner
    spec:
      containers:
      - image: go_perf_dashboard_testrunner
        imagePullPolicy: Never
        name: go-perf-dashboard-testrunner
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: testrunner-env