apiVersion: v1
kind: Service
metadata:
  name: testrunner-service
spec:
  selector:
    app: testrunner
  ports:
    - protocol: TCP
      port: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testrunner-deployment
  labels:
    app: testrunner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testrunner
  template:
    metadata:
      labels:
        app: testrunner
    spec:
      containers:
      - image: go_perf_dashboard_testrunner
        imagePullPolicy: Always
        name: go-perf-dashboard-testrunner
        ports:
        - containerPort: 8081